# constants.py
HEROES = sorted(
    [
        "Ginger",
        "Iris",
        "Isaac",
        "Julius",
        "Fafnir",
        "Nebula",
        "Dante",
        "Richter",
        "Octavia",
        "Polaris",
        "Martha",
        "Oya",
        "Hackebeil",
        "Yasmine",
        "Jhu",
        "Artemis",
        "Corvus",
        "Kayla",
        "Tempus",
        "Maya",
        "Aidan",
        "Arachne",
        "Tristan",
        "Dunkler Stern",
        "Orion",
        "Folio",
        "Morrigan",
        "Champi und Gnon",
        "Kai",
        "Cornelius",
        "Satori",
        "Luther",
        "Jorgen",
        "Astrid",
        "Lillith",
        "Soleil",
        "Gesichtsloser",
        "Astaroth",
        "Alvanor",
        "Chabba",
        "Karkh",
        "Elmir",
        "Lian",
        "Quing Mao",
        "Rufus",
        "Ziri",
        "Keira",
        "Dorian",
        "Galahad",
        "Mojo",
        "Phobos",
        "Heidi",
        "Thea",
        "XeSha",
        "Aurora",
        "Amira",
        "Celeste",
        "Sebastian",
        "Kaskade",
        "Peppy",
        "Draufgänger",
        "Markus",
        "Ishmael",
        "Electra",
        "Guus",
        "Krista",
        "Byrna",
        "Ninja Turtles",
        "Helios",
        "Lars",
        "Fuchs",
        "Andvari",
        "Peech",
        "Somna",
        "Lara Croft",
        "Jet",
        "Drayne",
    ]
)

GK_POSITIONS = [
    "Festung 1",
    "Festung 2",
    "Festung 3",
    "Festung 4",
    "Festung 5",
    "Festung 6",
    "Festung 7",
    "Leuchtturm 1",
    "Leuchtturm 2",
    "Leuchtturm 3",
    "Akademie 1",
    "Akademie 2",
    "Akademie 3",
    "Kaserne 1",
    "Kaserne 2",
    "Kaserne 3",
    "Gießerei 1",
    "Gießerei 2",
    "Gießerei 3",
    "Gießerei 4",
]

TEAM_NAMES = [
    "Nicki",
    "Nikozahn",
    "Nixdewiss",
    "Laura",
    "Kaio",
    "Kyros",
    "Klinge",
    "Lord Fuuu",
    "Yotilar",
    "Gollum",
    "Chrissomat",
    "Moe",
    "Sharan",
    "Oromis",
]
